// Generated by the Supabase MCP from project fyvvyjsninswdxnzwpdg.
// Regenerate after every migration; do not hand-edit.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      allowed_emails: {
        Row: {
          added_by: string | null
          created_at: string
          email: string
          note: string | null
          role: Database['public']['Enums']['app_role']
        }
        Insert: {
          added_by?: string | null
          created_at?: string
          email: string
          note?: string | null
          role?: Database['public']['Enums']['app_role']
        }
        Update: {
          added_by?: string | null
          created_at?: string
          email?: string
          note?: string | null
          role?: Database['public']['Enums']['app_role']
        }
        Relationships: []
      }
      boat_members: {
        Row: {
          boat_id: string
          created_at: string
          role: Database['public']['Enums']['app_role']
          user_id: string
        }
        Insert: {
          boat_id: string
          created_at?: string
          role: Database['public']['Enums']['app_role']
          user_id: string
        }
        Update: {
          boat_id?: string
          created_at?: string
          role?: Database['public']['Enums']['app_role']
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'boat_members_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      boats: {
        Row: {
          created_at: string
          engine_make_model: string | null
          fuel_capacity_gal: number | null
          home_lat: number | null
          home_lng: number | null
          home_port: string | null
          id: string
          make_model: string | null
          name: string
          tide_station_id: string | null
          year: number | null
        }
        Insert: {
          created_at?: string
          engine_make_model?: string | null
          fuel_capacity_gal?: number | null
          home_lat?: number | null
          home_lng?: number | null
          home_port?: string | null
          id?: string
          make_model?: string | null
          name: string
          tide_station_id?: string | null
          year?: number | null
        }
        Update: {
          created_at?: string
          engine_make_model?: string | null
          fuel_capacity_gal?: number | null
          home_lat?: number | null
          home_lng?: number | null
          home_port?: string | null
          id?: string
          make_model?: string | null
          name?: string
          tide_station_id?: string | null
          year?: number | null
        }
        Relationships: []
      }
      crew: {
        Row: {
          boat_id: string
          created_at: string
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          id: string
          name: string
          user_id: string | null
        }
        Insert: {
          boat_id: string
          created_at?: string
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          id?: string
          name: string
          user_id?: string | null
        }
        Update: {
          boat_id?: string
          created_at?: string
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          id?: string
          name?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'crew_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      documents: {
        Row: {
          boat_id: string
          created_at: string
          created_by: string | null
          expires_on: string | null
          file_name: string | null
          id: string
          label: string | null
          storage_path: string | null
          type: string
        }
        Insert: {
          boat_id: string
          created_at?: string
          created_by?: string | null
          expires_on?: string | null
          file_name?: string | null
          id?: string
          label?: string | null
          storage_path?: string | null
          type: string
        }
        Update: {
          boat_id?: string
          created_at?: string
          created_by?: string | null
          expires_on?: string | null
          file_name?: string | null
          id?: string
          label?: string | null
          storage_path?: string | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: 'documents_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      float_plan_crew: {
        Row: {
          crew_id: string
          float_plan_id: string
        }
        Insert: {
          crew_id: string
          float_plan_id: string
        }
        Update: {
          crew_id?: string
          float_plan_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'float_plan_crew_crew_id_fkey'
            columns: ['crew_id']
            isOneToOne: false
            referencedRelation: 'crew'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'float_plan_crew_float_plan_id_fkey'
            columns: ['float_plan_id']
            isOneToOne: false
            referencedRelation: 'float_plans'
            referencedColumns: ['id']
          },
        ]
      }
      float_plans: {
        Row: {
          boat_id: string
          closed_at: string | null
          created_at: string
          created_by: string | null
          departure_at: string
          departure_point: string | null
          destination_notes: string | null
          expires_at: string
          id: string
          planned_return_at: string
          shore_contact_name: string | null
          token: string
          trip_id: string | null
        }
        Insert: {
          boat_id: string
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          departure_at: string
          departure_point?: string | null
          destination_notes?: string | null
          expires_at: string
          id?: string
          planned_return_at: string
          shore_contact_name?: string | null
          token: string
          trip_id?: string | null
        }
        Update: {
          boat_id?: string
          closed_at?: string | null
          created_at?: string
          created_by?: string | null
          departure_at?: string
          departure_point?: string | null
          destination_notes?: string | null
          expires_at?: string
          id?: string
          planned_return_at?: string
          shore_contact_name?: string | null
          token?: string
          trip_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'float_plans_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'float_plans_trip_id_fkey'
            columns: ['trip_id']
            isOneToOne: false
            referencedRelation: 'trips'
            referencedColumns: ['id']
          },
        ]
      }
      maintenance_log: {
        Row: {
          boat_id: string
          cost: number | null
          created_at: string
          created_by: string | null
          engine_hours_at_service: number | null
          id: string
          notes: string | null
          performed_by: string | null
          service_date: string
          service_type: string
        }
        Insert: {
          boat_id: string
          cost?: number | null
          created_at?: string
          created_by?: string | null
          engine_hours_at_service?: number | null
          id?: string
          notes?: string | null
          performed_by?: string | null
          service_date: string
          service_type: string
        }
        Update: {
          boat_id?: string
          cost?: number | null
          created_at?: string
          created_by?: string | null
          engine_hours_at_service?: number | null
          id?: string
          notes?: string | null
          performed_by?: string | null
          service_date?: string
          service_type?: string
        }
        Relationships: [
          {
            foreignKeyName: 'maintenance_log_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      maintenance_schedule: {
        Row: {
          active: boolean
          annual_due_day: number | null
          annual_due_month: number | null
          boat_id: string
          category: string
          created_at: string
          due_at_hours_override: number | null
          due_on_date_override: string | null
          id: string
          interval_hours: number | null
          interval_months: number | null
          override_anchor_date: string | null
          service_type: string
        }
        Insert: {
          active?: boolean
          annual_due_day?: number | null
          annual_due_month?: number | null
          boat_id: string
          category?: string
          created_at?: string
          due_at_hours_override?: number | null
          due_on_date_override?: string | null
          id?: string
          interval_hours?: number | null
          interval_months?: number | null
          override_anchor_date?: string | null
          service_type: string
        }
        Update: {
          active?: boolean
          annual_due_day?: number | null
          annual_due_month?: number | null
          boat_id?: string
          category?: string
          created_at?: string
          due_at_hours_override?: number | null
          due_on_date_override?: string | null
          id?: string
          interval_hours?: number | null
          interval_months?: number | null
          override_anchor_date?: string | null
          service_type?: string
        }
        Relationships: [
          {
            foreignKeyName: 'maintenance_schedule_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      points_of_interest: {
        Row: {
          boat_id: string
          category: string
          created_at: string
          created_by: string | null
          depth_ft: number | null
          id: string
          lat: number
          lng: number
          name: string
          notes: string | null
        }
        Insert: {
          boat_id: string
          category?: string
          created_at?: string
          created_by?: string | null
          depth_ft?: number | null
          id?: string
          lat: number
          lng: number
          name: string
          notes?: string | null
        }
        Update: {
          boat_id?: string
          category?: string
          created_at?: string
          created_by?: string | null
          depth_ft?: number | null
          id?: string
          lat?: number
          lng?: number
          name?: string
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'points_of_interest_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
      trip_passengers: {
        Row: {
          crew_id: string
          trip_id: string
        }
        Insert: {
          crew_id: string
          trip_id: string
        }
        Update: {
          crew_id?: string
          trip_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'trip_passengers_crew_id_fkey'
            columns: ['crew_id']
            isOneToOne: false
            referencedRelation: 'crew'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'trip_passengers_trip_id_fkey'
            columns: ['trip_id']
            isOneToOne: false
            referencedRelation: 'trips'
            referencedColumns: ['id']
          },
        ]
      }
      trip_photos: {
        Row: {
          caption: string | null
          created_at: string
          id: string
          sort_order: number
          storage_path: string
          trip_id: string
          uploaded_by: string | null
        }
        Insert: {
          caption?: string | null
          created_at?: string
          id?: string
          sort_order?: number
          storage_path: string
          trip_id: string
          uploaded_by?: string | null
        }
        Update: {
          caption?: string | null
          created_at?: string
          id?: string
          sort_order?: number
          storage_path?: string
          trip_id?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'trip_photos_trip_id_fkey'
            columns: ['trip_id']
            isOneToOne: false
            referencedRelation: 'trips'
            referencedColumns: ['id']
          },
        ]
      }
      trip_sites: {
        Row: {
          site_id: string
          trip_id: string
        }
        Insert: {
          site_id: string
          trip_id: string
        }
        Update: {
          site_id?: string
          trip_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'trip_sites_site_id_fkey'
            columns: ['site_id']
            isOneToOne: false
            referencedRelation: 'points_of_interest'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'trip_sites_trip_id_fkey'
            columns: ['trip_id']
            isOneToOne: false
            referencedRelation: 'trips'
            referencedColumns: ['id']
          },
        ]
      }
      trips: {
        Row: {
          boat_id: string
          conditions_fetched_at: string | null
          conditions_snapshot: Json | null
          conditions_status: string | null
          created_at: string
          created_by: string | null
          departure_time: string | null
          distance_mi: number | null
          distance_nm: number | null
          end_lat: number | null
          end_lng: number | null
          engine_hours_end: number | null
          engine_hours_start: number | null
          fuel_added_gal: number | null
          fuel_cost_usd: number | null
          fuel_from_full_end_gal: number | null
          fuel_from_full_start_gal: number | null
          fuel_price_per_gal: number | null
          fuel_used_gal: number | null
          hours_run: number | null
          id: string
          notes: string | null
          return_time: string | null
          route_points: Json | null
          start_lat: number | null
          start_lng: number | null
          trip_date: string
          updated_at: string
        }
        Insert: {
          boat_id: string
          conditions_fetched_at?: string | null
          conditions_snapshot?: Json | null
          conditions_status?: string | null
          created_at?: string
          created_by?: string | null
          departure_time?: string | null
          distance_nm?: number | null
          end_lat?: number | null
          end_lng?: number | null
          engine_hours_end?: number | null
          engine_hours_start?: number | null
          fuel_added_gal?: number | null
          fuel_from_full_end_gal?: number | null
          fuel_from_full_start_gal?: number | null
          fuel_price_per_gal?: number | null
          id?: string
          notes?: string | null
          return_time?: string | null
          route_points?: Json | null
          start_lat?: number | null
          start_lng?: number | null
          trip_date: string
          updated_at?: string
        }
        Update: {
          boat_id?: string
          conditions_fetched_at?: string | null
          conditions_snapshot?: Json | null
          conditions_status?: string | null
          created_at?: string
          created_by?: string | null
          departure_time?: string | null
          distance_nm?: number | null
          end_lat?: number | null
          end_lng?: number | null
          engine_hours_end?: number | null
          engine_hours_start?: number | null
          fuel_added_gal?: number | null
          fuel_from_full_end_gal?: number | null
          fuel_from_full_start_gal?: number | null
          fuel_price_per_gal?: number | null
          id?: string
          notes?: string | null
          return_time?: string | null
          route_points?: Json | null
          start_lat?: number | null
          start_lng?: number | null
          trip_date?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'trips_boat_id_fkey'
            columns: ['boat_id']
            isOneToOne: false
            referencedRelation: 'boats'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_float_plan: { Args: { p_token: string }; Returns: Json }
    }
    Enums: {
      app_role: 'crew' | 'viewer'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ['crew', 'viewer'],
    },
  },
} as const
